name: Pipeline

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master

jobs:
  install-test-build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          npm install -g aws-cdk
          pip install . --upgrade

          pip list
          docker --version
          python --version
          node --version
          npm --version

      - name: IntegrationTest
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
          pytest b_aws_cdk_parallel_test/integration/tests

      - name: Install
        run: pip install wheel twine

      - name: Build
        run: python setup.py sdist bdist_wheel

      - name: Upload
        run: twine upload dist/* -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
